# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.2
_src_path: https://github.com/run-llama/template-workflow-document-qa
project_name: document-qa
project_title: Document Qa
